housefinder-dev/src/main/java/com/fuhousefinder/entity/HistoryOrder.java
package com.fuhousefinder.entity;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class HistoryOrder {

    private String house_name;
    private int room_number;
    private int house_id;
    private String status;
    private LocalDateTime history_date;

    public HistoryOrder() {
    }

    public HistoryOrder(String house_name, int room_number, int house_id, String status, LocalDateTime history_date) {
        this.house_name = house_name;
        this.room_number = room_number;
        this.house_id = house_id;
        this.status = status;
        this.history_date = history_date;
    }

    public String dateString() {
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        return history_date.format(format);
    }

    public String getStatusString() {
        switch (status) {
            case "Approve":
                return "Đã xác nhận";
            case "Pending":
                return "Đang chờ xác nhận";
            case "CheckOut":
                return "Đã trả phòng";
            case "Reject":
                return "Đã bị từ chối";
            case "Cancel":
                return "Đã hủy";
        }
        return "";
    }

    public String getHouse_name() {
        return house_name;
    }

    public void setHouse_name(String house_name) {
        this.house_name = house_name;
    }

    public int getRoom_number() {
        return room_number;
    }

    public void setRoom_number(int room_number) {
        this.room_number = room_number;
    }

    public int getHouse_id() {
        return house_id;
    }

    public void setHouse_id(int house_id) {
        this.house_id = house_id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getHistory_date() {
        return history_date;
    }

    public void setHistory_date(LocalDateTime history_date) {
        this.history_date = history_date;
    }

}

housefinder-dev/src/main/java/com/fuhousefinder/entity/RoomModel.java
package com.fuhousefinder.entity;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author hp
 */
public class RoomModel {

    private int roomId;
    private int houseId;
    private int postId;
    private String roomNumber;
    private String floorNumber;
    private String status;
    private String descriptionRoom;
    private double price;
    private double area;
    private LocalDateTime createDate;
    private LocalDateTime updateDate;

    private List<UtilityModel> utilities;

    public RoomModel(int roomId, String roomNumber) {
        this.roomId = roomId;
        this.roomNumber = roomNumber;
    }

    public RoomModel(int roomId, int houseId, String roomNumber, String status, double price, double area, LocalDateTime createDate, LocalDateTime updateDate) {
        this.roomId = roomId;
        this.houseId = houseId;
        this.roomNumber = roomNumber;
        this.status = status;
        this.price = price;
        this.area = area;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    public String getStatusString() {
        return "1".equals(status) ? "Còn phòng" : "Hết phòng";
    }

    public List<UtilityModel> getUtilities() {
        return utilities;
    }

    public String getUtilityString() {
        if (utilities == null || utilities.isEmpty()) {
            return "";
        }
        return utilities.stream()
                .map(UtilityModel::getName)
                .collect(Collectors.joining(" , "));
    }

    public void setUtilities(List<UtilityModel> utilities) {
        this.utilities = utilities;
    }

    public RoomModel(int roomId, int houseId, int postId, String roomNumber, String floorNumber, String status, String descriptionRoom, double price, double area, LocalDateTime createDate, LocalDateTime updateDate) {
        this.roomId = roomId;
        this.houseId = houseId;
        this.postId = postId;
        this.roomNumber = roomNumber;
        this.floorNumber = floorNumber;
        this.status = status;
        this.descriptionRoom = descriptionRoom;
        this.price = price;
        this.area = area;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    public RoomModel() {
    }

    public int getRoomId() {
        return roomId;
    }

    public void setRoomId(int roomId) {
        this.roomId = roomId;
    }

    public int getHouseId() {
        return houseId;
    }

    public void setHouseId(int houseId) {
        this.houseId = houseId;
    }

    public int getPostId() {
        return postId;
    }

    public void setPostId(int postId) {
        this.postId = postId;
    }

    public String getRoomNumber() {
        return roomNumber;
    }

    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    public String getFloorNumber() {
        return floorNumber;
    }

    public void setFloorNumber(String floorNumber) {
        this.floorNumber = floorNumber;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDescriptionRoom() {
        return descriptionRoom;
    }

    public void setDescriptionRoom(String descriptionRoom) {
        this.descriptionRoom = descriptionRoom;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getArea() {
        return area;
    }

    public void setArea(double area) {
        this.area = area;
    }

    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    

}

housefinder-dev/src/main/java/com/fuhousefinder/controller/room/HistoryOrderServlet.java
package com.fuhousefinder.controller.room;

import com.fuhousefinder.dao.OrderDAO;
import com.fuhousefinder.dao.UserDAO;
import com.fuhousefinder.entity.HistoryOrder;
import com.fuhousefinder.entity.User;
import java.io.IOException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.util.List;


@WebServlet(name="HistoryOrder", urlPatterns={"/historyorder"})
public class HistoryOrderServlet extends HttpServlet {
   
    
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        OrderDAO dao = new OrderDAO();
        UserDAO userdao = new UserDAO();
        HttpSession session = request.getSession();
        User user = (User) session.getAttribute("user");
        int tenantId = userdao.getTenantIDByUserID(user.getId());
        List<HistoryOrder> historyOrder = dao.getHistoryOrderByTenantId(tenantId);
        request.setAttribute("history", historyOrder);
        request.getRequestDispatcher("pages/room/historyorder.jsp").forward(request, response);       
    } 

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        processRequest(request, response);
    } 

    
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        processRequest(request, response);
    }

    
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

housefinder-dev/src/main/webapp/pages/room/addRoom.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Thêm Phòng</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
        <!-- CSS here -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/owl.carousel.min.css">
        <link rel="stylesheet" href="css/magnific-popup.css">
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="css/themify-icons.css">
        <link rel="stylesheet" href="css/nice-select.css">
        <link rel="stylesheet" href="css/flaticon.css">
        <link rel="stylesheet" href="css/gijgo.css">
        <link rel="stylesheet" href="css/animate.min.css">
        <link rel="stylesheet" href="css/slicknav.css">

        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f0f2f5;
                margin: 0;
                padding: 20px;
                margin-top: 150px;
            }
            .container {
                max-width: 800px;
                margin: auto;
                padding: 20px;
                background-color: #fff;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }
            h1 {
                text-align: center;
                color: #333;
            }
            label {
                display: block;
                margin-top: 10px;
                font-weight: bold;
                color: #555;
            }
            input[type="text"], textarea {
                width: 100%;
                padding: 10px;
                margin-top: 5px;
                border: 1px solid #ddd;
                border-radius: 4px;
            }
            input[type="file"] {
                margin-top: 10px;
            }
            .image-preview {
                display: flex;
                flex-wrap: wrap;
                margin-top: 10px;
            }
            .image-preview div {
                position: relative;
                margin-right: 10px;
                margin-bottom: 10px;
            }
            .image-preview img {
                width: 100px;
                height: 100px;
                object-fit: cover;
                border-radius: 4px;
            }
            .image-preview .remove-image {
                position: absolute;
                top: 5px;
                right: 5px;
                background: rgba(0, 0, 0, 0.5);
                color: #fff;
                border: none;
                border-radius: 50%;
                width: 20px;
                height: 20px;
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;
            }
            .btn-submit {
                width: 100%;
                padding: 10px;
                margin-top: 20px;
                background-color: #28a745;
                color: #fff;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                font-size: 16px;
            }
            .btn-submit:hover {
                background-color: #218838;
            }
            .error-message {
                color: red;
                font-size: 12px;
                margin-top: 5px;
            }

        </style>
    </head>
    <body>
        <jsp:include page="/pages/header/header.jsp"></jsp:include>
            <div class="container">
                <h1>Thêm Phòng</h1>
                <form id="addRoomForm" enctype="multipart/form-data">

                    <input hidden="" type="text" id="house_id" name="house_id" value="${house_id}" required>
                <input hidden="" type="text" id="house_id" name="house_id" value="${roomid}" required>

                <label for="room_number">Room Number:</label>
                <input type="number" id="room_number" name="room_number" required>
                <div class="error-message" id="error-room_number"></div>


                <label for="price">Price:</label>
                <input type="text" min="100000" max="1000000000" step="100000" id="price" name="price" required>
                <div class="error-message" id="error-price"></div>

                <label for="area">Area:</label>
                <input type="text" min="0.1" max="100" step="0.1" id="area" name="area" required>
                <div class="error-message" id="error-area"></div>

                <label for="description_room">Description:</label>
                <textarea id="description_room" name="description_room" required></textarea>
                <div class="error-message" id="error-description_room"></div>

                <label for="status">Status:</label>
                <input type="text" id="status" name="status" required>
                <div class="error-message" id="error-status"></div>

                <!--            <label for="room_images">Upload Room Images:</label>
                            <input type="file" id="room_images" name="room_images[]" multiple accept="image/*">
                            <div class="image-preview" id="imagePreview"></div>-->

                <input type="submit" value="Add Room" class="btn-submit">
            </form>
        </div>




        <jsp:include page="/pages/footer/footer.jsp"></jsp:include>
        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

        <script src="js/vendor/modernizr-3.5.0.min.js"></script>
        <script src="js/vendor/jquery-1.12.4.min.js"></script>
        <script src="js/popper.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/owl.carousel.min.js"></script>
        <script src="js/isotope.pkgd.min.js"></script>
        <script src="js/ajax-form.js"></script>
        <script src="js/waypoints.min.js"></script>
        <script src="js/jquery.counterup.min.js"></script>
        <script src="js/imagesloaded.pkgd.min.js"></script>
        <script src="js/scrollIt.js"></script>
        <script src="js/jquery.scrollUp.min.js"></script>
        <script src="js/wow.min.js"></script>
        <script src="js/nice-select.min.js"></script>
        <script src="js/jquery.slicknav.min.js"></script>
        <script src="js/jquery.magnific-popup.min.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/gijgo.min.js"></script>
        <!--contact js-->
        <script src="js/contact.js"></script>
        <script src="js/jquery.ajaxchimp.min.js"></script>
        <script src="js/jquery.form.js"></script>
        <script src="js/jquery.validate.min.js"></script>
        <script src="js/mail-script.js"></script>
        <script src="js/main.js"></script>
        <script>
            // Hàm kiểm tra dữ liệu form
            function validateForm() {
                let isValid = true;

                // Xóa thông báo lỗi trước đó
                document.getElementById('houseIdError').innerText = '';

                document.getElementById('roomNumberError').innerText = '';
                document.getElementById('floorNumberError').innerText = '';
                document.getElementById('statusError').innerText = '';
                document.getElementById('descriptionRoomError').innerText = '';
                document.getElementById('priceError').innerText = '';
                document.getElementById('areaError').innerText = '';
                //        document.getElementById('createDateError').innerText = '';

                // Lấy giá trị các trường
                const houseId = document.getElementById('house_id').value;
                const roomNumber = document.getElementById('room_number').value;
                const floorNumber = document.getElementById('floor_number').value;
                const status = document.getElementById('status').value;
                const descriptionRoom = document.getElementById('description_room').value;
                const price = document.getElementById('price').value;
                const area = document.getElementById('area').value;
                //        const createDate = document.getElementById('create_date').value;

                // Kiểm tra ID Nhà
                if (houseId === '') {
                    document.getElementById('houseIdError').innerText = 'ID Nhà là bắt buộc.';
                    isValid = false;
                }



                // Kiểm tra Số Phòng
                if (roomNumber === '' || isNaN(roomNumber) || !Number.isInteger(Number(roomNumber))) {
                    document.getElementById('roomNumberError').innerText = 'Số Phòng là một số nguyên';
                    isValid = false;

                }
                //        else if (roomNumber.length > 255) {
                //            document.getElementById('roomNumberError').innerText = 'Số Phòng không được vượt quá 255 ký tự.';
                //            isValid = false;
                //        }

                // Kiểm tra Số Tầng
                if (floorNumber === '') {
                    document.getElementById('floorNumberError').innerText = 'Số Tầng là bắt buộc.';
                    isValid = false;
                } else if (floorNumber.length > 255) {
                    document.getElementById('floorNumberError').innerText = 'Số Tầng không được vượt quá 255 ký tự.';
                    isValid = false;
                }

                // Kiểm tra Trạng Thái
                if (status === '') {
                    document.getElementById('statusError').innerText = 'Trạng thái là bắt buộc.';
                    isValid = false;
                } else if (status.length > 255) {
                    document.getElementById('statusError').innerText = 'Trạng thái không được vượt quá 255 ký tự.';
                    isValid = false;
                }

                // Kiểm tra Mô Tả
                if (descriptionRoom === '') {
                    document.getElementById('descriptionRoomError').innerText = 'Mô tả là bắt buộc.';
                    isValid = false;
                } else if (descriptionRoom.length > 255) {
                    document.getElementById('descriptionRoomError').innerText = 'Mô tả không được vượt quá 255 ký tự.';
                    isValid = false;
                }

                // Kiểm tra Giá
                if (price === '') {
                    document.getElementById('priceError').innerText = 'Giá là bắt buộc.';
                    isValid = false;
                }

                // Kiểm tra Diện Tích
                if (area === '') {
                    document.getElementById('areaError').innerText = 'Diện tích là bắt buộc.';
                    isValid = false;
                }

                //        // Kiểm tra Ngày Tạo
                //        if (createDate === '') {
                //            document.getElementById('createDateError').innerText = 'Ngày tạo là bắt buộc.';
                //            isValid = false;
                //        }

                return isValid;
            }
        </script>
    </body>
</html>

housefinder-dev/src/main/webapp/pages/room/historyorder.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>FU House Finder</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS here -->
        <link rel="stylesheet" href="${pageContext.request.contextPath}/css/bootstrap.min.css">
        <link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css">
        <style>
            .bradcam_area {
                padding: 20px 0 102px 0;
            }
            .update{
                min-height: 600px
            }
            .table{
                overflow: scroll
            }
        </style>

    </head>

    <body>

        <jsp:include page="/pages/header/header.jsp"></jsp:include>
            <div class="bradcam_area bradcam_bg_1"></div>
            <div class="container update text-center">

            <c:if test="${empty history}">
                <h1 class="mt-5">Bạn chưa có lịch sử đặt phòng</h1>
            </c:if>
            <c:if test="${not empty history }">
                <h1 class="text-center mb-5 mt-5">Lịch sử yêu cầu thuê nhà</h1>
                <table class="table table-borderless">
                    <tr>
                        <td>STT</td>
                        <td>Tên nhà</td>
                        <td>Số phòng</td>
                        <td>Trạng thái</td>
                        <td>Thời gian</td>
                    </tr>
                    <c:forEach items="${history}" var="history" varStatus="loop">
                        <tr>
                            <td>${loop.index + 1}</td>
                            <td>${history.house_name}</td>
                            <td>${history.room_number}</td>
                            <td>${history.getStatusString()}</td>
                            <td>${history.dateString()}</td>
                        </tr>
                    </c:forEach>
                </table>
            </c:if>


        </div>

        <jsp:include page="/pages/footer/footer.jsp"></jsp:include>

            <!-- JS here -->
            <script src="${pageContext.request.contextPath}/js/vendor/jquery-1.12.4.min.js"></script>
        <script src="${pageContext.request.contextPath}/js/bootstrap.min.js"></script>
        <script src="${pageContext.request.contextPath}/js/main.js"></script>
    </body>

</html>

housefinder-dev/src/main/webapp/pages/room/updateRoom.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>FU House Finder</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSS here -->
        <link rel="stylesheet" href="${pageContext.request.contextPath}/css/bootstrap.min.css">
        <link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css">
        <style>
            .container {
                border-radius: 8px;
                padding: 30px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);

            }

            h1 {
                margin-bottom: 30px;
            }

            .btn-primary {
                background-color: #007bff;
                border-color: #007bff;
            }

            .form-group {
                display: flex;
                flex-direction: column;
                align-items: flex-start;
            }

            .form-group label {
                margin-bottom: 5px;
            }

            .form-group select {
                width: 100%;
                max-width: 100%;
                display: block;
            }
        </style>
        <style>
            .bradcam_area {
                padding: 20px 0 102px 0;
            }
            .camera img{
                height: 40px;
                border-radius: 50%;
            }
            .rounded-circle{
                height: 170px;
                width: 170px;
                border-radius: 50%;
            }
            .alert-top-right {
                position: fixed;
                top: 100px;
                right: 20px;
                z-index: 1050; /* Đảm bảo rằng thông báo xuất hiện trên các thành phần khác */
            }
            .update{
                width: 600px;
                margin-top: 20px;
                margin-bottom: 30px
            }
        </style>

    </head>

    <body>

        <jsp:include page="/pages/header/header.jsp"></jsp:include>
            <div class="bradcam_area bradcam_bg_1"></div>
            <div class="container update">
                <h1>Cập Nhật Phòng</h1>
                <form id="updateRoomForm" action="update_room" method="post" onsubmit="return validateUpdateRoomForm()">
                    <input type="hidden" name="room_id" value="${roomid}">
                <input type="hidden" class="form-control" id="house_id" name="house_id" value="${house_id}" required>

                <div class="form-group">
                    <label for="room_number">Số Phòng<samp style="color: red">*</samp></label>
                    <input type="number" class="form-control" id="room_number" name="room_number" value="${room.roomNumber}" required min="0">
                    <div id="roomNumberError" class="text-danger"></div>
                </div>


                <div class="form-group">
                    <label for="price">Giá<samp style="color: red">*</samp></label>
                    <input type="number" step="100000" class="form-control" id="price" name="price" value="${room.price}" required min="0">
                    <div id="priceError" class="text-danger"></div>
                </div>
                <div class="form-group">
                    <label for="area">Diện Tích<samp style="color: red">*</samp></label>
                    <input type="number" step="0.5" class="form-control" id="area" name="area" value="${room.area}" required min="0">
                    <div id="areaError" class="text-danger"></div>
                </div>

                <div class="form-group">
                    <label for="utilities">Tiện ích</label>
                    <div id="utilities">
                        <c:forEach var="utility" items="${allUtilities}">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="utilities" value="${utility.id}" <c:if test="${fn:contains(room.utilityString, utility.name)}">checked</c:if>>
                                <label class="form-check-label">${utility.name}</label>
                            </div>
                        </c:forEach>
                    </div>
                </div>
                <div class="row d-flex justify-content-center">
                    <a class="btn btn-primary" href="javascript:history.back()">Quay lại</a>
                    <button type="submit" class="btn btn-primary ml-4">Cập Nhật Phòng</button>                    
                </div>
            </form>
        </div>

        <jsp:include page="/pages/footer/footer.jsp"></jsp:include>

            <!-- JS here -->
            <script src="${pageContext.request.contextPath}/js/vendor/jquery-1.12.4.min.js"></script>
        <script src="${pageContext.request.contextPath}/js/bootstrap.min.js"></script>
        <script src="${pageContext.request.contextPath}/js/main.js"></script>
    </body>

</html>